/**
 * Giải thích từng cột (hiện ở tooltip header bảng). Dùng được cả client & server.
 */

export const GL_FIELD_DOCS: Record<string, string> = {
  ID: "Khóa tự tăng của dòng sổ cái.",
  ComCode: "Công ty ghi sổ (= cổng thanh toán, map từ PaymentGatewayName).",
  DataSource: "Nguồn dữ liệu sinh ra dòng này (ORDERS, PAYPAL, ...).",
  JournalTypeCode: "Mã nghiệp vụ chuẩn (từ bảng JournalType). VD ORD_REV_PRODUCT_FULFILLED = doanh thu sản phẩm của order đã fulfill.",
  DocNum: "Số chứng từ. Single: ASI-{yyyyMMdd}-{AccountingEventID}. Bulk: ASB-{yyyyMMdd}-{AccountingEventID nhỏ nhất trong nhóm}. Các dòng cùng DocNum luôn cân Nợ = Có.",
  PostingGroupKey: "Chỉ có với Bulk: khóa gom nhóm ComCode|JournalTypeCode|Ngày|InputCurr|FncCurr|Partner|TaxID|BankAccount. Các event cùng khóa được cộng lại thành 1 chứng từ.",
  PostBatchID: "Lần bấm Post đã sinh ra dòng này (xem trang Posting). Dùng để truy vết và Unpost theo lô.",
  ReferenceTxnID: "Mã giao dịch gốc (TransactionID của event). Bulk để trống vì 1 dòng gom nhiều giao dịch.",
  OrderID: "Mã order gốc (chỉ Single).",
  RefNum: "Số tham chiếu (với Orders = OrderId; chỉ Single).",
  TransDate: "Ngày hạch toán (= PostingDate của event; với Orders = FulfilledAt).",
  DocDate: "Ngày chứng từ (= TransDate).",
  Period: "Kỳ kế toán YYYYMM.",
  AccountCode: "Tài khoản kế toán (CoA). Lấy từ JournalLineRule.NormalDr/CrAccountSource → cột account tương ứng trên JournalType.",
  BankAccountNumber: "Số tài khoản ngân hàng/PSP (PayPal, Stripe...). Orders không có.",
  PartnerCode: "Đối tượng công nợ. Doanh thu order = INDIVIDUALS (khách lẻ); lợi nhuận seller = email seller.",
  PartnerTaxID: "Mã định danh (TaxID) của partner trong bảng Partners — dùng theo dõi công nợ đúng đối tượng.",
  InputCurr: "Đồng tiền giao dịch (nguyên tệ).",
  FncCurr: "Đồng tiền hạch toán của công ty (Company.FunctionalCurrency).",
  InputDr: "Số tiền nguyên tệ bên Nợ (dòng Credit thì = 0). Có thể âm nếu NegativeMode = SIGNED.",
  InputCr: "Số tiền nguyên tệ bên Có (dòng Debit thì = 0).",
  XRate: "Tỷ giá đã dùng. Cùng tiền = 1; khác tiền lấy từ bảng Exrate theo kỳ.",
  RateType: "Cách quy đổi: MUL (nhân) hoặc DIV (chia).",
  AccountedDr: "Số tiền Nợ đã quy đổi sang FncCurr = InputDr × (hoặc ÷) XRate.",
  AccountedCr: "Số tiền Có đã quy đổi sang FncCurr.",
  Description: "Diễn giải = MemoTemplate của rule | TransactionID (Single) hoặc | số event (Bulk).",
  BalanceImpact: "Vế của dòng: Debit (Nợ) hoặc Credit (Có).",
  IsReversal: "Dự phòng cho bút toán đảo (chưa dùng).",
  ReverseID: "Dự phòng: ID dòng bị đảo (chưa dùng).",
  IsReval: "Dự phòng: đánh giá lại tỷ giá (chưa dùng).",
  Segment: "Dự phòng: phân đoạn báo cáo (chưa dùng).",
  AddDate: "Thời điểm tạo dòng.",
  ModifiedDate: "Thời điểm sửa gần nhất.",
};

export const EVENT_FIELD_DOCS: Record<string, string> = {
  AccountingEventID: "Khóa event. 1 event = 1 giao dịch nguồn × 1 JournalLineRule (1 cặp Nợ/Có).",
  ComCode: "Công ty ghi sổ (= cổng thanh toán).",
  DataSource: "Nguồn: ORDERS.",
  JournalTypeCode: "Nghiệp vụ. 1 order fulfilled sinh tối đa 4 nghiệp vụ: PRODUCT, SHIPADD, TAX, SELLER_PROFIT.",
  TransactionID: "Mã giao dịch chuẩn hóa: ORD-{OrderId}-{yyyyMMdd FulfilledAt}.",
  EventSeq: "= JournalLineRule.RuleSeq, dùng để join lại rule khi Post.",
  LineSeq: "Thứ tự dòng trong event (luôn 1).",
  PairCode: "Cặp bút toán của rule: CONTRA_TRANS, BANK_CONTRA, FEE_BANK...",
  AmountSource: "Số tiền lấy từ đâu: PRODUCT = Σ Quantity×UnitPrice; SHIPADD = Σ ShippingFee+AdditionalCost; TAX = Σ TaxFee; SELLER_PROFIT = Σ Profit.",
  PostingDate: "Ngày hạch toán = FulfilledAt.",
  Period: "Kỳ YYYYMM của PostingDate.",
  OrderID: "Mã order gốc.",
  RefNum: "Số tham chiếu (= OrderId).",
  SourceID: "Khóa nguồn: {OrderId}|{yyyyMMdd}.",
  InputCurr: "Tiền giao dịch (Orders = USD).",
  FncCurr: "Tiền hạch toán của công ty.",
  Amount: "Số tiền signed, CHƯA nhân AmountFactor, CHƯA tách Nợ/Có.",
  BankAccountNumber: "Tài khoản ngân hàng/PSP nguồn (Orders trống).",
  BankGLAccount: "TK ngân hàng (JournalType.BankAccount).",
  ContraAccount: "TK đối ứng (JournalType.ContraAccount). VD 13122001 Người mua trả tiền trước, 33102001 Phải trả seller.",
  TransAccount: "TK nghiệp vụ (JournalType.TransAccount). VD 51112001 Doanh thu, 63202001 Giá vốn seller.",
  FeeAccount: "TK phí (JournalType.FeeAccount).",
  PartnerCode: "Partner: Fixed = INDIVIDUALS hoặc From Source = seller (match TaxID → SellerEmail + StoreName).",
  PartnerTaxID: "TaxID của partner trong bảng Partners.",
  PartnerName: "Tên partner (VD FFT-FFT ARG).",
  Description: "Tên nghiệp vụ (JournalType.JournalType).",
  BalanceImpact: "Không dùng ở event.",
  PostStatus: "NEW = chờ post; POSTED = đã vào GLTrans; ERROR = lỗi (xem ErrorMessage); SKIPPED = bỏ qua theo rule.",
  PostedDocNum: "DocNum trên GLTrans sau khi post.",
  PostingGroupKey: "Khóa gom Bulk khi post.",
  PostBatchID: "Lần post đã ghi sổ event này.",
  PostedAt: "Thời điểm post.",
  ErrorStage:
    "Lỗi phát sinh ở bước BUILD (sửa master rồi build lại; riêng POSTED_KEY_CHANGED phải Unpost chứng từ cũ trước — xem ErrorMessage) hay POST (post lại để thử lại).",
  ErrorMessage: "Lý do lỗi/bỏ qua.",
  SourceHash: "SHA256 dữ liệu nguồn — phát hiện nguồn thay đổi sau khi đã post.",
  ItemCodes: "Các ItemCode (dòng order) tạo nên event, dạng JSON. Dùng chặn ghi sổ trùng khi item đã POSTED dưới khóa khác (POSTED_KEY_CHANGED).",
  BuildBatchID: "Lần build đã tạo/cập nhật event.",
  AddDate: "Thời điểm tạo.",
  ModifiedDate: "Thời điểm sửa gần nhất.",
};

export const POSTING_BATCH_FIELD_DOCS: Record<string, string> = {
  PostBatchID: "Mã lần post. Mỗi lần bấm Post Single hoặc Post Bulk tạo 1 batch.",
  DataSource: "Nguồn giới hạn khi post (trống = tất cả).",
  Classify: "Single (mỗi event 1 chứng từ) hoặc Bulk (gom nhiều event thành 1 chứng từ).",
  ComCodeList: "Các công ty trong lần post.",
  PeriodFrom: "Kỳ bắt đầu của phạm vi post.",
  PeriodTo: "Kỳ kết thúc của phạm vi post.",
  StartedAt: "Bắt đầu chạy.",
  EndedAt: "Kết thúc chạy.",
  Status: "RUNNING / SUCCESS / FAILED / UNPOSTED (đã gỡ hết GL của batch).",
  InsertedRows: "Số dòng GLTrans đã ghi.",
  PostedEvents: "Số event chuyển sang POSTED.",
  ErrorEvents: "Số event lỗi khi post.",
  SkippedEvents: "Số event bị bỏ qua.",
  ErrorMessage: "Thông báo lỗi.",
};
