/** Danh sách cột file order (dùng được ở client) */
export type ColumnKind = "text" | "number" | "date" | "datetime";

/** 46 cột theo đúng thứ tự file order mẫu */
export const ORDER_COLUMNS: [name: string, kind: ColumnKind][] = [
  ["OrderId", "text"],
  ["ItemCode", "text"],
  ["SKU", "text"],
  ["ProductSKU", "text"],
  ["VariantName", "text"],
  ["Domain", "text"],
  ["Quantity", "number"],
  ["StoreName", "text"],
  ["ItemStatus", "text"],
  ["LastUpdatedAt", "datetime"],
  ["PaidAt", "datetime"],
  ["LastUpdatedDateAt", "date"],
  ["PaidDateAt", "date"],
  ["LastUpdatedTimeAt", "text"],
  ["PaidTimeAt", "text"],
  ["FulfilledAt", "date"],
  ["TrackingNumber", "text"],
  ["Carrier", "text"],
  ["UnitPrice", "number"],
  ["ShippingFee", "number"],
  ["TotalPrice", "number"],
  ["BuyerName", "text"],
  ["BuyerEmail", "text"],
  ["BuyerAddress1", "text"],
  ["BuyerAddress2", "text"],
  ["BuyerPhone", "text"],
  ["BuyerCity", "text"],
  ["BuyerProvince", "text"],
  ["BuyerCountry", "text"],
  ["BuyerZip", "text"],
  ["BuyerCountryCode", "text"],
  ["BuyerProvinceCode", "text"],
  ["SellerEmail", "text"],
  ["TransactionId", "text"],
  ["Profit", "number"],
  ["TaxID", "text"],
  ["PlatformProductSKU", "text"],
  ["Group", "text"],
  ["GroupQuantity", "number"],
  ["SupplierCost", "number"],
  ["PaymentGatewayId", "text"],
  ["PaymentGatewayName", "text"],
  ["GatewayType", "text"],
  ["FulfillmentCost", "number"],
  ["AdditionalCost", "number"],
  ["TaxFee", "number"],
];

export const REQUIRED_ORDER_COLUMNS = ["OrderId", "ItemCode", "ItemStatus", "Quantity", "UnitPrice", "PaymentGatewayName"];
